---

- hosts: docker-host-nodes
  sudo: yes
  roles:
    - run

- hosts: docker-containers
  roles:
    - infinispan-server
  tasks:
    - name: check ssh
      debug: var=ansible_ssh_port
    # add private key to containers
    # this should be changed in non-local mode: ssh between containers works
    - copy: src=~/.ssh/id_rsa dest=/root/.ssh/id_rsa
    - command: chmod 700 /root/.ssh/id_rsa
